### ISSUE TITLE
Leaked snmp community in check-dell-server.sh

### ISSUE THREAD

**Issue by jan-vitek** [bridrod/Nagios#1]
Hi,

I just wanted to let you know that the check-dell-server.sh script does not use the given snmp community attribute and instead it uses your hardcoded secret community.

**Comment by bridrod** [comment]
Thank you for that! I guess I left it while I was doing some troubleshooting and copied it from my LAB.
Committed the change.
Regards and happy new year! :)
Rod
    On Monday, January 4, 2021, 10:25:21 AM EST, Jan Vitek <notifications@github.com> wrote:  
 
 


Hi,

I just wanted to let you know that the check-dell-server.sh script does not use the given snmp community attribute and instead it uses your hardcoded secret community.
